[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "apscheduler>=3.11.0",
    "click>=8.1.8",
    "pyzmq>=26.2.0",
]

[project.scripts]
controller = "controller.__main__:controller"
